---
name: Network UPS Tools
version: dev
slug: nut
description: Manage battery backup (UPS) devices
url: https://github.com/hassio-addons/addon-nut
codenotary: codenotary@frenck.dev
startup: system
arch:
  - aarch64
  - amd64
  - armv7
init: false
uart: true
udev: true
usb: true
hassio_api: true
hassio_role: manager
homeassistant_api: true
ports:
  3493/tcp: null
ports_description:
  3493/tcp: Network UPS Tools
options:
  users:
    - username: ""
      password: ""
      instcmds:
        - all
      actions: []
  devices:
    - name: myups
      driver: usbhid-ups
      port: auto
      config: []
  mode: netserver
  shutdown_host: "false"
  # Example configurations (uncomment to use):
  
  # For USB-connected UPS:
  # devices:
  #   - name: myups
  #     driver: usbhid-ups
  #     port: auto
  #     config: []
  
  # For APC Smart-UPS with Network Card (SNMP):
  # devices:
  #   - name: smart_ups
  #     driver: snmp-ups
  #     port: 192.168.1.50  # NMC2 IP address
  #     config:
  #       - community = "private"  # SNMP community
  #       - snmp_version = "v1"   # or v2c, v3
  
  # For IPMI-based PDUs:
  # powerman:
  #   enabled: true
  #   devices:
  #     - name: pdu1
  #       type: ipmipower
  #       host: 192.168.1.100
  #       username: admin
  #       password: changeme
  #       nodes: "outlet[1-8]"
  
  # For APC AP7900B (8-outlet switched PDU):
  # powerman:
  #   enabled: true
  #   devices:
  #     - name: apc_rack_pdu
  #       type: apc
  #       host: 192.168.1.75
  #       username: apc
  #       password: apc
  #       nodes: "outlet[1-8]"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  users:
    - username: str
      password: password
      instcmds:
        - str
      actions:
        - str
      upsmon: list(master|slave)?
  devices:
    - name: str
      driver: str
      port: str
      powervalue: int?
      config:
        - str
      # PowerMan specific options
      powerman_host: str?
      powerman_port: int?
      powerman_device: str?
  # PowerMan configuration section
  powerman:
    enabled: bool?
    devices:
      - name: str
        type: str  # e.g., ipmipower, baytech, apc, etc.
        host: str
        username: str?
        password: password?
        nodes: str?  # Node mapping
  mode: list(netserver|netclient)
  shutdown_host: bool
  list_usb_devices: bool?
  remote_ups_name: str?
  remote_ups_host: str?
  remote_ups_password: password?
  remote_ups_user: str?
  upsd_maxage: int?
  upsmon_deadtime: int?
  i_like_to_be_pwned: bool?
  leave_front_door_open: bool?
